- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy a config file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: remove Old contents
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download App contents
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true