- name: Playbook for frontend
  hosts: all
  become: yes
  tasks:
    - name: Install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start mysql
      ansible.builtin.systemd_service:
        name: mysqld
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Setting up MySQL password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1


#print_task_heading "Setting up MySQL password"
#echo 'show databases' | mysql -h mysql-dev.shujathdevops.online -uroot -p${mysql_root_password} &>>${LOG}
#if [ $? -ne 0 ]; then
#mysql_secure_installation --set-root-pass ${mysql_root_password} &>>$LOG
#fi
#print_status $?
