- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy a config file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import app pre req
  ansible.builtin.import_role:
     name: common
     tasks_from: app-pre-req

- name: Start Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true