- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Setting up MySQL password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
