- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Install multi python packages PyMySQL cryptography
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.shujathdevops.online
- name: Install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Install multi python packages PyMySQL cryptography
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    filter: version
    login_host: mysql-dev.shujathdevops.online
  register: mysql_connection_output

- name: print password
  ansible.builtin.debug:
    msg: "{{ mysql_connection_output}}"

- name: Setting up MySQL password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
